--- #YAML:1.0
name:                OODoc
version:             1.00
abstract:            Object Oriented Documentation
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Bundle::Template::Magic:       0
    File::Slurp:                   9999.12
    Pod::Man:                      2.12
    Template::Magic::HTML:         1.02
    Test::More:                    0.47
    Test::Pod:                     1.26
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mark Overmeer
