# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OODoc
version:      0.94
version_from: version
installdirs:  site
requires:
    Bundle::Template::Magic:       0
    Pod::Man:                      2.12
    Template::Magic::HTML:         1.02
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
