--- #YAML:1.0
name:               OODoc
version:            1.06
abstract:           Object Oriented Documentation
author:
    - Mark Overmeer
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bundle::Template::Magic:  0
    File::Slurp:          9999.12
    IO::Scalar:           2.11
    OODoc::Template:      0.12
    Pod::Man:             2.12
    Template::Magic::HTML:  1.02
    Test::More:           0.47
    Test::Pod:            1.26
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
