=head1 NAME

OODoc::Text::Chapter - collects the information of one chapter

=head1 INHERITANCE

 OODoc::Text::Chapter
   is a OODoc::Text::Structure
   is a OODoc::Text
   is a OODoc::Object

=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 OVERLOADED

overload: B<'""' (stringification)>

=over 4

See L<OODoc::Text/"OVERLOADED">

=back

overload: B<'==' and '!='>

=over 4

See L<OODoc::Text/"OVERLOADED">

=back

overload: B<'cmp' (string comparison)>

=over 4

See L<OODoc::Text/"OVERLOADED">

=back

=head1 METHODS

=head2 Constructors

$obj-E<gt>B<emptyExtension>(CONTAINER)

=over 4

See L<OODoc::Text::Structure/"Constructors">

=back

OODoc::Text::Chapter-E<gt>B<new>(OPTIONS)

=over 4

 Option     --Defined in     --Default
 container    OODoc::Text      new(manual)
 description  OODoc::Text      ''
 level        OODoc::Text::Structure  1
 linenr       OODoc::Text      <required>
 manual                        undef
 name         OODoc::Text      undef
 type         OODoc::Text      'Chapter'

. container => OBJECT

. description => STRING

. level => INTEGER

. linenr => INTEGER

. manual => OBJECT

=over 4

The manual in which this chapter is described.

=back

. name => STRING

. type => STRING

=back

=head2 Inheritance knowledge

$obj-E<gt>B<extends>([OBJECT])

=over 4

See L<OODoc::Object/"Inheritance knowledge">

=back

=head2 Attributes

$obj-E<gt>B<container>([OBJECT])

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<description>

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<level>

=over 4

See L<OODoc::Text::Structure/"Attributes">

=back

$obj-E<gt>B<name>

=over 4

See L<OODoc::Text/"Attributes">

=back

$obj-E<gt>B<niceName>

=over 4

See L<OODoc::Text::Structure/"Attributes">

=back

$obj-E<gt>B<type>

=over 4

See L<OODoc::Text/"Attributes">

=back

=head2 Location

$obj-E<gt>B<findEntry>(NAME)

=over 4

See L<OODoc::Text::Structure/"Location">

=back

$obj-E<gt>B<manual>([NAME])

=over 4

See L<OODoc::Text/"Location">

=back

$obj-E<gt>B<path>

=over 4

See L<OODoc::Text::Structure/"Location">

=back

$obj-E<gt>B<unique>

=over 4

See L<OODoc::Text/"Location">

=back

$obj-E<gt>B<where>

=over 4

See L<OODoc::Text/"Location">

=back

=head2 Collected

$obj-E<gt>B<all>(METHOD, PARAMETERS)

=over 4

See L<OODoc::Text::Structure/"Collected">

=back

$obj-E<gt>B<example>(OBJECT)

=over 4

See L<OODoc::Text/"Collected">

=back

$obj-E<gt>B<examples>

=over 4

See L<OODoc::Text/"Collected">

=back

$obj-E<gt>B<findDescriptionObject>

=over 4

See L<OODoc::Text/"Collected">

=back

$obj-E<gt>B<isEmpty>

=over 4

See L<OODoc::Text::Structure/"Collected">

=back

$obj-E<gt>B<openDescription>

=over 4

See L<OODoc::Text/"Collected">

=back

=head2 Subroutines

$obj-E<gt>B<addSubroutine>(OBJECTS)

=over 4

See L<OODoc::Text::Structure/"Subroutines">

=back

$obj-E<gt>B<setSubroutines>(ARRAY)

=over 4

See L<OODoc::Text::Structure/"Subroutines">

=back

$obj-E<gt>B<subroutine>(NAME)

=over 4

See L<OODoc::Text::Structure/"Subroutines">

=back

$obj-E<gt>B<subroutines>

=over 4

See L<OODoc::Text::Structure/"Subroutines">

=back

=head2 Commonly used functions

$obj-E<gt>B<filenameToPackage>(FILENAME)

OODoc::Text::Chapter-E<gt>B<filenameToPackage>(FILENAME)

=over 4

See L<OODoc::Object/"Commonly used functions">

=back

$obj-E<gt>B<mkdirhier>(DIRECTORY)

OODoc::Text::Chapter-E<gt>B<mkdirhier>(DIRECTORY)

=over 4

See L<OODoc::Object/"Commonly used functions">

=back

=head2 Manual Repository

$obj-E<gt>B<addManual>(MANUAL)

=over 4

See L<OODoc::Object/"Manual Repository">

=back

$obj-E<gt>B<mainManual>(NAME)

=over 4

See L<OODoc::Object/"Manual Repository">

=back

$obj-E<gt>B<manuals>

=over 4

See L<OODoc::Object/"Manual Repository">

=back

$obj-E<gt>B<manualsForPackage>(NAME)

=over 4

See L<OODoc::Object/"Manual Repository">

=back

$obj-E<gt>B<packageNames>

=over 4

See L<OODoc::Object/"Manual Repository">

=back

=head2 Sections

A chapters consists of a list of sections, which may contain subsections.

$obj-E<gt>B<section>(NAME|OBJECT)

=over 4

With a NAME, the section within this chapter with that name is
returned.  With an OBJECT (which must be a L<OODoc::Text::Section|OODoc::Text::Section>),
a new section is added to the end of the list.

=back

$obj-E<gt>B<sections>([SECTIONS])

=over 4

Returns a list of all sections in this chapter.

=back

=head1 DIAGNOSTICS

Error: manual definition requires manual object

=over 4

A call to L<addManual()|OODoc::Object/"Manual Repository"> expects a new manual object (a L<OODoc::Manual|OODoc::Manual>),
however an incompatible thing was passed.  Usually, intended was a call
to L<manualsForPackage()|OODoc::Object/"Manual Repository"> or L<mainManual()|OODoc::Object/"Manual Repository">.

=back

=head1 SEE ALSO

This module is part of OODoc distribution version 1.02,
built on November 09, 2007. Website: F<http://perl.overmeer.net/oodoc/>

=head1 LICENSE

Copyrights 2003-2007 by Mark Overmeer. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

