=head1 NAME

OODoc::Text::Example - one example for the use of a subroutine

=head1 INHERITANCE

 OODoc::Text::Example
   is a OODoc::Text
   is a OODoc::Object

=head1 DESCRIPTION

Each L<OODoc::Text|OODoc::Text> element can have a list of examples,
which are each captured in a separate object as described
in this manual page.

=head1 OVERLOADED

=over 4

=item overload: B<'""' (stringification)>

See L<OODoc::Text/"OVERLOADED">

=item overload: B<'==' and '!='>

See L<OODoc::Text/"OVERLOADED">

=item overload: B<'cmp' (string comparison)>

See L<OODoc::Text/"OVERLOADED">

=back

=head1 METHODS

=head2 Constructors

=over 4

=item OODoc::Text::Example-E<gt>B<new>(OPTIONS)

 -Option     --Defined in     --Default
  container    OODoc::Text      <required>
  description  OODoc::Text      ''
  linenr       OODoc::Text      <required>
  name         OODoc::Text      undef
  type         OODoc::Text      'Example'

=over 2

=item container => OBJECT

=item description => STRING

=item linenr => INTEGER

=item name => STRING

=item type => STRING

=back

=back

=head2 Inheritance knowledge

=over 4

=item $obj-E<gt>B<extends>([OBJECT])

See L<OODoc::Object/"Inheritance knowledge">

=back

=head2 Attributes

=over 4

=item $obj-E<gt>B<container>([OBJECT])

See L<OODoc::Text/"Attributes">

=item $obj-E<gt>B<description>

See L<OODoc::Text/"Attributes">

=item $obj-E<gt>B<name>

See L<OODoc::Text/"Attributes">

=item $obj-E<gt>B<type>

See L<OODoc::Text/"Attributes">

=back

=head2 Location

=over 4

=item $obj-E<gt>B<manual>([NAME])

See L<OODoc::Text/"Location">

=item $obj-E<gt>B<unique>

See L<OODoc::Text/"Location">

=item $obj-E<gt>B<where>

See L<OODoc::Text/"Location">

=back

=head2 Collected

=over 4

=item $obj-E<gt>B<example>(OBJECT)

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<examples>

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<findDescriptionObject>

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<openDescription>

See L<OODoc::Text/"Collected">

=back

=head2 Commonly used functions

=over 4

=item $obj-E<gt>B<filenameToPackage>(FILENAME)

OODoc::Text::Example-E<gt>B<filenameToPackage>(FILENAME)

See L<OODoc::Object/"Commonly used functions">

=item $obj-E<gt>B<mkdirhier>(DIRECTORY)

OODoc::Text::Example-E<gt>B<mkdirhier>(DIRECTORY)

See L<OODoc::Object/"Commonly used functions">

=back

=head2 Manual Repository

=over 4

=item $obj-E<gt>B<addManual>(MANUAL)

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<mainManual>(NAME)

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<manuals>

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<manualsForPackage>(NAME)

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<packageNames>

See L<OODoc::Object/"Manual Repository">

=back

=head1 DIAGNOSTICS

=over 4

=item Error: manual definition requires manual object

A call to L<addManual()|OODoc::Object/"Manual Repository"> expects a new manual object (a L<OODoc::Manual|OODoc::Manual>),
however an incompatible thing was passed.  Usually, intended was a call
to L<manualsForPackage()|OODoc::Object/"Manual Repository"> or L<mainManual()|OODoc::Object/"Manual Repository">.

=back

=head1 SEE ALSO

This module is part of OODoc distribution version 1.06,
built on January 26, 2011. Website: F<http://perl.overmeer.net/oodoc/>

=head1 LICENSE

Copyrights 2003-2011 by Mark Overmeer. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

