=head1 NAME

OODoc::Text::Subroutine - collects information about one documented sub

=head1 INHERITANCE

 OODoc::Text::Subroutine
   is a OODoc::Text
   is a OODoc::Object

=head1 DESCRIPTION

Perl has various things we can call "sub" (for "subroutine") one
way or the other.  This object tries to store all types of them:
methods, funtion, ties, and overloads. Actually, these are the
most important parts of the documentation.  The share more than
they differ.

=head1 OVERLOADED

=over 4

=item overload: B<'""' (stringification)>()

See L<OODoc::Text/"OVERLOADED">

=item overload: B<'==' and '!='>()

See L<OODoc::Text/"OVERLOADED">

=item overload: B<'cmp' (string comparison)>()

See L<OODoc::Text/"OVERLOADED">

=back

=head1 METHODS

=head2 Constructors

=over 4

=item OODoc::Text::Subroutine-E<gt>B<new>(OPTIONS)

 -Option     --Defined in     --Default
  container    OODoc::Text      <required>
  description  OODoc::Text      ''
  linenr       OODoc::Text      <required>
  name         OODoc::Text      undef
  parameters                    undef
  type         OODoc::Text      <required>

=over 2

=item container => OBJECT

=item description => STRING

=item linenr => INTEGER

=item name => STRING

=item parameters => STRING

=item type => STRING

=back

=back

=head2 Inheritance knowledge

=over 4

=item $obj-E<gt>B<extends>([OBJECT])

=back

=head2 Attributes

=over 4

=item $obj-E<gt>B<container>([OBJECT])

See L<OODoc::Text/"Attributes">

=item $obj-E<gt>B<description>()

See L<OODoc::Text/"Attributes">

=item $obj-E<gt>B<name>()

See L<OODoc::Text/"Attributes">

=item $obj-E<gt>B<parameters>()

The parameter list for the subroutine is returned as string.  The
result may be C<undef> or empty.

=item $obj-E<gt>B<type>()

See L<OODoc::Text/"Attributes">

=back

=head2 Location

=over 4

=item $obj-E<gt>B<location>(MANUAL)

Try to figure-out what the location for the subroutine is within the
MANUAL page.  Have a look at all levels of extension for this
sub-routine's documentation and decides the best enclosing
chapter, section and subsection.  Then return that object for the
current manual.

=item $obj-E<gt>B<manual>([NAME])

See L<OODoc::Text/"Location">

=item $obj-E<gt>B<path>()

Returns the path of the text structure which contains this subroutine.

=item $obj-E<gt>B<unique>()

See L<OODoc::Text/"Location">

=item $obj-E<gt>B<where>()

See L<OODoc::Text/"Location">

=back

=head2 Collected

=over 4

=item $obj-E<gt>B<collectedOptions>()

Returns a list of option-default combinations on this subroutine.

=item $obj-E<gt>B<default>(NAME|OBJECT)

In case of a NAME, a default object for this method is looked up.  This
does not search through super classes, but solely which is defined with
this subroutine.  When passed an OBJECT of type OODoc::Text::Default
that will be stored.

=item $obj-E<gt>B<defaults>()

Returns a list of all defaults as defined by this documentation item in
one manual.

=item $obj-E<gt>B<diagnostic>(OBJECT)

Add a new diagnostic message (a OODoc::Text::Diagnostic object) to the
list already in this object.  You can not look for a message because
these names are without use.

=item $obj-E<gt>B<diagnostics>()

Returns a list of all diagnostics.

=item $obj-E<gt>B<example>(OBJECT)

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<examples>()

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<findDescriptionObject>()

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<findOption>(NAME)

Does a little more thorough job than L<option()|OODoc::Text::Subroutine/"Collected"> bu searching the inherited
options for this subroutine as well.

=item $obj-E<gt>B<openDescription>()

See L<OODoc::Text/"Collected">

=item $obj-E<gt>B<option>(NAME|OBJECT)

In case of a NAME, the option object for this method is looked up.  This
does not search through super classes, but solely which is defined with
this subroutine.  When passed an OBJECT of type OODoc::Text::Option
that will be stored.

=item $obj-E<gt>B<options>()

Returns a list of all options as defined by this documentation item in
one manual.

=back

=head2 Commonly used functions

=over 4

=item $obj-E<gt>B<filenameToPackage>(FILENAME)

=item OODoc::Text::Subroutine-E<gt>B<filenameToPackage>(FILENAME)

See L<OODoc::Object/"Commonly used functions">

=item $obj-E<gt>B<mkdirhier>(DIRECTORY)

=item OODoc::Text::Subroutine-E<gt>B<mkdirhier>(DIRECTORY)

See L<OODoc::Object/"Commonly used functions">

=back

=head2 Manual Repository

=over 4

=item $obj-E<gt>B<addManual>(MANUAL)

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<mainManual>(NAME)

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<manuals>()

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<manualsForPackage>(NAME)

See L<OODoc::Object/"Manual Repository">

=item $obj-E<gt>B<packageNames>()

See L<OODoc::Object/"Manual Repository">

=back

=head1 DIAGNOSTICS

=over 4

=item Error: manual definition requires manual object

A call to L<addManual()|OODoc::Object/"Manual Repository"> expects a new manual object (a L<OODoc::Manual|OODoc::Manual>),
however an incompatible thing was passed.  Usually, intended was a call
to L<manualsForPackage()|OODoc::Object/"Manual Repository"> or L<mainManual()|OODoc::Object/"Manual Repository">.

=item Warning: subroutine $name extended by different type:

Any description of a subroutine classifies it as method, tie, overload or
whatever.  Apparently, this indicated subroutine is defined being of a
different type on these both places, and there is an inheritance relation
between these places.

In very rare cases, this warning can be ignored, but usually these
situation is errorneous of confusing for the users of the library.

=item Warning: subroutine $self location conflict: $here $super

The location of subroutine descriptions must be consistent over the
manual pages.  You may change the level of clearness about the
exact location (place in the chapter in one page, and in a subsection
in the next), as long as it is not conflicting (the subsection must
be a part of the chapter).

=back

=head1 SEE ALSO

This module is part of OODoc distribution version 2.00,
built on January 11, 2013. Website: F<http://perl.overmeer.net/oodoc/>

=head1 LICENSE

Copyrights 2003-2013 by [Mark Overmeer]. For other contributors see ChangeLog.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
See F<http://www.perl.com/perl/misc/Artistic.html>

