
=head1 NAME

My::Name::Space - just an example




=head1 DESCRIPTION

General description of the module.  Some people make this very long,
before the start of the explanation of the functions or methods.  My
preference is to explain only the really really important stuff which
should be read by everyone.  All less import things are kept in a
chapter named DETAILS after the explanation of functions and stuff such
that important things come first.



=head1 METHODS

take whatever you need in the order you wish to define it (order of the
chapters is only determined by the output templates of the formatter)

=head2 Constructors

It is useful to use sections to group methods or functions when the number
of them grows large.  The methods and functions will get sorted
alphabetically, and you do not want the "new" to disappear far down in
the list.

$obj-E<gt>B<clone>

=over 4

Make a copy of the object.

=back

$obj-E<gt>B<new>(OPTIONS)

=over 4

Create a new object.  Read all about the =option, =default, =example, and
so on in the manual-page of the OODoc::Parser::Markov.

=back

=head2 Accessors

And so on.  Do not forget the C<=cut>'s!


=head1 FUNCTIONS





=head1 DETAILS

Here I put the detailed explanation, especially about how different methods
and functions work together.

Again: do not forget the next line!!!





=head1 REFERENCES

See the OODoc website at L<http://perl.overmeer.net/oodoc/> for more details.

=head1 COPYRIGHTS

Module version 0.95.
Written by Mark Overmeer (mark@overmeer.net).  See the ChangeLog for
other contributors.

Copyright (c) 2003-2006 by the author(s). All rights reserved.  This program
is free software; you can redistribute it and/or modify it under the
same terms as Perl itself.


